-- =============================================================================
-- V010  Email attachments live on the outbox row
--
-- The dispatch job originally carried attachment info as transient queue data,
-- which meant an outbox-sweep retry re-sent the message WITHOUT its
-- certificate. The outbox row is the durable record; the attachment pointer
-- belongs on it.
-- =============================================================================

ALTER TABLE email_logs
  ADD COLUMN IF NOT EXISTS attachment_url  VARCHAR(600),
  ADD COLUMN IF NOT EXISTS attachment_name VARCHAR(255);

COMMENT ON COLUMN email_logs.attachment_url IS
  'Short-lived signed URL n8n fetches; regenerated by the processor when expired.';
